import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.1.0/samples
 */

plugins {
    kotlin("jvm") version ("2.2.20")
    alias(libs.plugins.google.protobuf)
}

repositories {
    mavenCentral()
}

buildscript {
    dependencies {
        classpath(libs.google.protobuf.gradle.plugin)
        classpath(libs.jetbrains.kotlin.gradle.plugin)
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.32.1"
    }
}

dependencies {
    implementation(libs.google.protobuf.kotlin)
    implementation(libs.jetbrains.kotlin.stdlib)
    implementation(libs.jetbrains.kotlinx.cli)
}

kotlin {
    compilerOptions {
        apiVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_2)
        languageVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_2)
        jvmTarget.set(JvmTarget.JVM_21)
        allWarningsAsErrors = true
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    dependsOn(":generateProto")
}
